# Generated by Django 4.0.4 on 2022-05-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=8)),
                ('released', models.DateField()),
                ('imdbrating', models.CharField(max_length=4)),
            ],
        ),
    ]
