# Generated by Django 4.0.4 on 2022-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetail',
            name='released',
            field=models.CharField(max_length=50),
        ),
    ]
